name: Remote

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          path: docs
      - name: Check remote
        run: git remote -v
        working-directory: docs
      - name: Check computed remote
        run: echo https://${{ secrets.SERVICE_ACCOUNT_TOKEN }}@github.com/${{ github.repository }}.git/
        working-directory: docs