name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit empty message
        run: |
          git config user.name "tensei-engine-bot"
          git config user.email "144497878+tensei-engine@users.noreply.github.com"
          git commit --allow-empty -m "chore: test action"
          git push
        working-directory: docs