name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          path: docs
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: docs
      - name: Debug
        run: |
          echo Email: ${{ steps.import_gpg.outputs.email }}
          echo Name: ${{ steps.import_gpg.outputs.name }}
      - name: Commit empty message
        run: |
          git remote set-url origin https://${{ secrets.SERVICE_ACCOUNT_TOKEN }}@github.com/${{ github.repository }}.git/
          echo "$(git config --get user.name)"
          echo "$(git config --get user.email)"
          git commit --allow-empty -m "chore: test action"
          git push
        working-directory: docs
